/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Elen (https://sketchfab.com/Kitty999)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/cup-of-cappuccino-04f2c34a3df94e58be97c2830e7e462a
title: Cup of cappuccino
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/src/assets/cup/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.3}>
            <group position={[-0.09, 0.3, 0.09]} rotation={[-0.06, -0.65, 0.23]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
              
            </group>
            <group position={[-0.11, 0.03, 0.11]} rotation={[0.49, -0.96, -0.15]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
            </group>
            <group position={[-0.18, 0.03, 0.1]} rotation={[-0.7, 0.79, 0.25]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            </group>
            <group position={[-0.2, 0.03, 0.02]} rotation={[-0.79, 0.59, 0.51]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
            </group>
            <group position={[0.04, 0.3, 0.14]} rotation={[-1.39, 1.33, 1.74]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
            </group>
            <group position={[-0.14, 0.29, 0.01]} rotation={[0.16, 0.27, 0.07]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
            </group>
            <group position={[-0.08, 0.31, 0.02]} rotation={[3.13, -0.67, -2.4]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            </group>
            <group position={[-0.13, 0.29, -0.08]} rotation={[-0.48, -1.04, -0.42]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
            </group>
            <group position={[-0.08, 0.3, -0.05]} rotation={[-2.43, 0.07, 3.13]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
            </group>
            <group position={[-0.03, 0.29, -0.15]} rotation={[-1.42, 1.26, 0.86]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
            </group>
            <group position={[0.04, 0.03, 0.18]} rotation={[-1.12, -0.4, 0.25]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
            </group>
            <group position={[-0.03, 0.03, 0.19]} rotation={[-2.15, 1.33, 1.74]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
            </group>
            <group position={[-0.13, 0.03, 0.18]} rotation={[-2.13, 1.33, 1.74]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
            </group>
            <group position={[0, 0.27, 0]} rotation={[-Math.PI, 1.03, -Math.PI]} scale={[3.3, 3.3, 3.3]}>
              <mesh geometry={nodes.Object_31.geometry} material={materials.Coffee} />
            </group>
            <group position={[0, 0.02, 0]} scale={3.3}>
              <mesh geometry={nodes.Object_33.geometry} material={materials.material} />
            </group>
            <group scale={3.3}>
              <mesh geometry={nodes.Object_35.geometry} material={materials.Plate} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/src/assets/cup/scene.gltf')
